// 2o procedimento/clientes/livros-react/src/LivroDados.js
import { useNavigate } from "react-router-dom"
import { ControleEditora } from "./controle/ControleEditora"
import { ControleLivro } from "./controle/ControleLivros"
import React from "react"

const controleLivro = new ControleLivro()
const controleEditora = new ControleEditora()


const LivroDados = () => {
    const navigate = useNavigate()
    const opcoes = controleEditora.getEditoras().map( editora => editora.codEditora)
    
    const [titulo,setTitulo] = React.useState("")
    const [resumo,setResumo] = React.useState("")
    const [autores,setAutores] = React.useState("")
    const [codEditora,setCodEditora] = React.useState(opcoes[0])

    const tratarCombo = (evento) => {
        setCodEditora(Number(evento.target.value))
    }

    const incluir = (evento) => {
        evento.preventDefault()
        const livro = {
            codigo : '',
            codEditora,
            titulo,
            resumo,
            autores : autores.split('\n')
        };
        console.log(livro)
        controleLivro.incluir(livro).then( () => {
            navigate('/');
        });

        
    }
    return (
        <main>
            <h1>Dados do Livro</h1>
            <form onSubmit={ (evento) => incluir(evento)}>
                <div className="form-group">
                    <label className="form-label">Título*</label>
                    <input required className="form-control mb-2" type="text" id="titulo" value={titulo} onChange={(evento)=> setTitulo(evento.target.value)}></input>
                </div>
                <div className="form-group">
                    <label className="form-label">Resumo</label>
                    <textarea className="form-control mb-2" id="resumo" value={resumo} onChange={ (evento) => setResumo(evento.target.value)}></textarea>
                </div>
                <div className="form-group">
                    <label className="form-label">Editora*</label>
                    <select className="form-select form-control mb-4" onChange={ (evento) => {tratarCombo(evento)}}>
                        {opcoes.map( (cod) => {
                            return (<option  key={cod} value={cod}>{controleEditora.getNomeEditora(cod)}</option>)
                        } )}

                    </select>
                </div>
                <div className="form-group">
                    <label className="form-label">Autores (1 por linha)*</label>
                    <textarea required className="form-control mb-2" value={autores} onChange={ (evento) => setAutores(evento.target.value)}></textarea>
                </div>
                <div>
                    <p>* Campo Obrigatório</p>
                </div>
                <div>
                    <button type="submit" className="btn btn-primary">Salvar Dados</button>
                </div>

            </form>
        </main>
    )
}

export default LivroDados

// 2o procedimento/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent implements OnInit {
  public livro:Livro = new Livro('',1,'','',[])

  public autoresForm:string = ''
  public editoras:Array<Editora> = []


  constructor(private servEditora:ControleEditoraService, private servLivro:ControleLivrosService, private router:Router){
    this.servEditora = servEditora
    this.servLivro = servLivro
    this.router = router
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras()
  }

  incluir = ():void=>{
    this.livro.autores = this.autoresForm.split('\n')
    console.log(this.livro)
    this.servLivro.incluir(this.livro).then( ()=> {
      this.router.navigateByUrl('/lista')
    })
  }
}

<main class="container">
    <h2>Dados do Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
        <label for="titulo" class="form-label">Título</label>
        <input type="text" class="form-control" name="titulo" required [(ngModel)]="livro.titulo" />
        <label for="resumo" class="form-label">Resumo</label>
        <textarea class="form-control" name="resumo" [(ngModel)]="livro.resumo" ></textarea>
        <label for="editora" class="form-label">Editora</label>
        <select class="form-select" name="editora" required [(ngModel)]="livro.codEditora">
            <option *ngFor="let editora of editoras" value={{editora.codEditora}} >{{editora.nome}}</option>
        </select>
        <label for="autores" class="form-label">Autores</label>
        <textarea class="form-control" name="autores" required [(ngModel)]="autoresForm"></textarea>
        <button type="submit" class="btn btn-primary mt-2">Salvar Dados</button>

    </form>
</main>
