// 2o procedimento/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleLivrosService } from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';
import { CommonModule} from '@angular/common';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit{
  public editoras:Array<Editora> = []
  public livros:Array<Livro> = []

  constructor(private servLivro:ControleLivrosService, private servEditora:ControleEditoraService){
    this.servLivro = servLivro
    this.servEditora = servEditora
  }

  async ngOnInit(): Promise<void> {
    this.editoras = this.servEditora.getEditoras()
    this.servLivro.obterLivros().then( livros => {
      this.livros = livros
    });
  }

  excluir = (cod:string):void => {
    this.servLivro.excluir(cod).then( () => {
      this.servLivro.obterLivros().then( livros => this.livros = livros);
    });
  }

  obterNome = (codEditora:number):string | undefined => {
    return this.servEditora.getNomeEditora(codEditora)
  }
}

<main class= "container ">
<h2>Catálogo de Livros</h2>
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <td>Título</td>
            <td>Resumo</td>
            <td>Editora</td>
            <td>Autores</td>
        </tr>
    </thead>
    <tbody class="table-striped">
        <tr *ngFor="let livro of livros">
            <td >{{livro.titulo}}
                <br/>
                <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
            </td>
            <td>{{livro.resumo}}</td>
            <td>{{obterNome(livro.codEditora)}}</td>
            <td>
                <ul >
                    <li *ngFor="let autor of livro.autores">
                        {{autor}}
                    </li>

                </ul>
            </td>
        </tr>

    </tbody>
</table>

</main>

// 2o procedimento/clientes/livros-react/src/LivroLista.js
import React from "react";
import { ControleLivro } from "./controle/ControleLivros";
import { ControleEditora } from "./controle/ControleEditora";


const controleLivro = new ControleLivro()
const controleEditora = new ControleEditora()



const LinhaLivro = ({livro, excluir})=>{
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora)

    return (
    <tr>
        <td >
            {livro.titulo} <br/>
            <button type="button" className="btn btn-danger" onClick={ (e) =>{
                e.preventDefault()
                excluir(livro._id)
            }}> Excluir </button>
        </td>
        <td>{livro.resumo}</td>
        <td>{nomeEditora}</td>
        <td>
            <ul>
                {livro.autores.map( (autor , index) => <li key={index}>{autor}</li>)}
            </ul>
        </td>
    </tr>
    )
}

const LivroLista = () =>{
    const [livros, setLivros] = React.useState([])
    const [carregado, setCarregado] = React.useState(false)

    // React does not like async functions on effect.
    React.useEffect( () => {
        async function fetchData(){
            controleLivro.obterLivros().then( (livros )=> {
                setLivros(livros);
                setCarregado(true);
            })
        }
        fetchData()
        // setLivros(controleLivro.obterLivros())
    }, [carregado])

    const excluirLivro = (codLivro) => {
        controleLivro.excluir(codLivro).then( () => {
            setCarregado(false)
        });
    }

    return (
        <main>
            <h1>Catálogo de Livros</h1>
            <table className="table">
                <thead className="table-dark">
                    <tr>
                        <th scope="col"> Título </th>
                        <th scope="col"> Resumo </th>
                        <th scope="col"> Editora </th>
                        <th scope="col"> Autores </th>
                    </tr>
                </thead>
                <tbody className="table-striped">
                    {livros.map( (livro, index) => <LinhaLivro livro={livro} excluir={excluirLivro} key={index} /> )}
                </tbody>
            </table>
        </main>
    )
}

export default LivroLista
