// 2o procedimento/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NgFor } from '@angular/common';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent implements OnInit {
  public livro:Livro = new Livro('',1,'','',[])

  public autoresForm:string = ''
  public editoras:Array<Editora> = []


  constructor(private servEditora:ControleEditoraService, private servLivro:ControleLivrosService, private router:Router){
    this.servEditora = servEditora
    this.servLivro = servLivro
    this.router = router
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras()
  }

  incluir = ():void=>{
    this.livro.autores = this.autoresForm.split('\n')
    console.log(this.livro)
    this.servLivro.incluir(this.livro).then( ()=> {
      this.router.navigateByUrl('/lista')
    })
  }
}

<main class="container">
    <h2>Dados do Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
        <label for="titulo" class="form-label">Título</label>
        <input type="text" class="form-control" name="titulo" required [(ngModel)]="livro.titulo" />
        <label for="resumo" class="form-label">Resumo</label>
        <textarea class="form-control" name="resumo" [(ngModel)]="livro.resumo" ></textarea>
        <label for="editora" class="form-label">Editora</label>
        <select class="form-select" name="editora" required [(ngModel)]="livro.codEditora">
            <option *ngFor="let editora of editoras" value={{editora.codEditora}} >{{editora.nome}}</option>
        </select>
        <label for="autores" class="form-label">Autores</label>
        <textarea class="form-control" name="autores" required [(ngModel)]="autoresForm"></textarea>
        <button type="submit" class="btn btn-primary mt-2">Salvar Dados</button>

    </form>
</main>

// 2o procedimento/clientes/livros-next/pages/LivroDados.tsx
import { ControleEditora } from "@/classes/controle/ControleEditora";
import { ControleLivro } from "@/classes/controle/ControleLivros";
import { Livro } from "@/classes/modelo/Livro";
import { Menu } from "@/componentes/Menu";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";
import {  useNavigate } from "react-router-dom";
import { controleLivro } from "./api/livros";



const LivroDados: NextPage = () => {
    
    const controleEditora:ControleEditora = new ControleEditora()
    const controleLivros :ControleLivro   = new ControleLivro();
    
    const opcoes = controleEditora.getEditoras().map( (editora) => {
        return {
            text: editora.nome,
            value: editora.codEditora
        }
    })

    const [titulo,setTitulo] = useState("")
    const [resumo,setResumo] = useState("")
    const [autores,setAutores] = useState("")
    const [codEditora,setCodEditora]= useState(opcoes[0])

    const router = useRouter()
    // const navigate = useNavigate()



    
    const tratarCombo = (evento:React.FormEvent<HTMLSelectElement>) => {
        const id:number = parseInt(evento.currentTarget.value) - 1 
        setCodEditora(opcoes[id])

    }
    

    const incluir = (evento:React.FormEvent<HTMLFormElement>) => {
        evento.preventDefault()
        const novoLivro = new Livro(
            '',
            codEditora.value,
            titulo,
            resumo,
            autores.split("/n")
        )
        controleLivro.incluir(novoLivro).then(
            ()=> {
                router.push("/LivroLista")
            }
        ) 
    }

    return (
        <div>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favcon.ico" />
            </Head>
            <Menu/>
            <main>
                <div className="container py-3">
                <h1 className="h1">Adicionar novo Livro</h1>

                <form onSubmit={ (evento) => incluir(evento)} >
                <div className="form-group">
                    <label className="form-label">Título*</label>
                    <input required className="form-control mb-2" type="text" id="titulo" value={titulo} onChange={(evento)=> setTitulo(evento.target.value)}></input>
                </div>
                <div className="form-group">
                    <label className="form-label">Resumo</label>
                    <textarea className="form-control mb-2" id="resumo" value={resumo} onChange={ (evento) => setResumo(evento.target.value)}></textarea>
                </div>
                <div className="form-group">
                    <label className="form-label">Editora*</label>
                    <select className="form-select form-control mb-4" onChange={(evento) => {tratarCombo(evento)}}>
                        {opcoes.map( (cod) => {
                            return (<option  key={cod.value} value={cod.value}>{controleEditora.getNomeEditora(cod.value)}</option>)
                        } )}

                    </select>
                </div>
                <div className="form-group">
                    <label className="form-label">Autores (1 por linha)*</label>
                    <textarea required className="form-control mb-2" value={autores} onChange={ (evento) => setAutores(evento.target.value)}></textarea>
                </div>
                <div>
                    <p>* Campo Obrigatório</p>
                </div>
                <div>
                    <button type="submit" className="btn btn-primary">Salvar Dados</button>
                </div>
                    
                </form>
                </div>
            </main>
        </div>
    )}

export default LivroDados;
